Repository Varying-Vagrant-Vagrants/custom-site-template-develop, pull requests merged in 2019-10, with the labels that each got.

#15 Fix 1943
  provision/vvv-init.sh
Labels: bug

#17 Cusotm Nginx Support and Updates
  provision/vvv-init.sh
  provision/vvv-nginx-default.conf
Labels: enhancement

#18 Sets stricter bash execution on the main provisioner
  provision/vvv-init.sh
Labels: enhancement, help wanted
